#[derive(Debug, strum::Display, PartialEq, Eq)]
pub enum ProtoToken {
    FullIdentifier(Vec<Vec<u8>>),
    Identifier(Vec<u8>),
    StringLiteral(String),
    IntLiteral(isize),
    Bool,
    String,
    Bytes,
    Float,
    Double,
    Colon,
    SemiColon,
    Syntax,
    Package,
    Option,
    Import,
    Message,
    Service,
    Enum,
    OneOf,
    Repeated,
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    OpenBracket,
    CloseBracket,
    Equals,
    Weak,
    Public,
    Reserved,
    Extend,
    Extensions,
    /// To is used for ranges `reserved 10 to max;`
    To,
    /// Max is interpreted as 2,147,483,647
    Max,
    Map,
    LessThan,
    GreaterThan,
    Comma,
    Comment(Vec<u8>),
}
